
export const alreadyStartedError = new Error('Task has already started.')
